---
ignition:
  config: {}
  timeouts: {}
networkd: {}
passwd:
  groups:
  - name: depot
    gid: 15000
    system: false
storage:
  files:
  - filesystem: root
    path: "/opt/mediadepot/bootstrap/depot-env.sh"
    mode: 493 #755
    contents:
      local: depot-env.sh
  - filesystem: root
    path: "/etc/systemd/system/media-storage.mount.d/base.conf"
    mode: 420 #644
    contents:
      inline: |
        [Unit]
        Requires = media-temp.mount
        After = media-temp.mount
  directories:
  # the /media directory is a tmpfs file system, so lets create a /media/temp directory thats bind mounted to the /mnt/temp
  # folder that's on the actual OS disk
  - filesystem: root
    mode: 493 #755
    path: "/mnt/temp/"
    user:
      id: 15000
    group:
      id: 15000

  - filesystem: root
    mode: 493 #755
    path: "/opt/mediadepot/apps/"
    user:
      id: 15000
    group:
      id: 15000
  - filesystem: root
    mode: 493
    path: "/opt/mediadepot/bootstrap/"
  - filesystem: root
    mode: 493
    path: "/etc/sysconfig/"
  - filesystem: root
    mode: 493
    path: "/etc/systemd/system/docker.service.d/"
systemd:
  units:
  - name: media-temp.mount
    enable: true
    contents: |-
      [Mount]
      What=/mnt/temp
      Where=/media/temp
      Type=none
      Options=bind

      [Install]
      WantedBy=local-fs.target
  - name: depot-env.service
    enabled: true
    contents: |-
      [Unit]
      Description=Generate Depot Environmental Files
      After=network-online.target
      Requires=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/opt/mediadepot/bootstrap/depot-env.sh
      RemainAfterExit=true
      StandardOutput=journal

      [Install]
      WantedBy=multi-user.target
