---
ignition:
  config: {}
  timeouts: {}
networkd: {}
passwd:
  groups:
  - name: depot
    gid: 15000
    system: false
storage:
  files:
  - filesystem: root
    path: "/opt/mediadepot/bootstrap/depot-env.sh"
    mode: 493 #755
    contents:
      local: depot-env.sh

  - filesystem: root
    path: "/etc/systemd/system/docker.service.d/block-docker.conf"
    mode: 493 #755
    contents:
      inline: |-
        # block docker.service until environmental variable files have been created.
        [Unit]
        After=depot-env.service
        Requires=depot-env.service


  directories:
  - filesystem: root
    mode: 493 #755
    path: "/opt/mediadepot/apps/"
    user:
      id: 15000
    group:
      id: 15000
  - filesystem: root
    mode: 493
    path: "/opt/mediadepot/bootstrap/"
systemd:
  - name: depot-env.service
    enabled: true
    contents: |-
      [Unit]
      Description=Generate Depot Environmental Files
      After=network-online.target
      Requires=network-online.target

      [Service]
      Type=oneshot
      ExecStart=/opt/mediadepot/bootstrap/depot-env.sh
      RemainAfterExit=true
      StandardOutput=journal

      [Install]
      WantedBy=multi-user.target
