---
ignition:
  config: {}
  timeouts: {}
networkd: {}
passwd:
  groups:
  - name: depot
    gid: 15000
    system: false
  users:
  - name: depot
    uid: 15000
    primary_group: depot
    no_user_group: true
    system: false
    shell: "/bin/bash"
storage:
  directories:
  - filesystem: root
    mode: 493 #755
    path: "/opt/mediadepot/apps/"
    user:
      id: 15000
    group:
      id: 15000
  - filesystem: root
    mode: 493
    path: "/opt/mediadepot/bootstrap/"
systemd: {}