---
ignition:
  config: {}
  timeouts: {}
networkd: {}
passwd: {}
storage:
  files:
    - filesystem: root
      path: "/opt/mediadepot/systemd/traefik/docker-compose.yml"
      mode: 493 #755
      contents:
        inline: |-
          version: '2'
          services:
            traefik:
              image: traefik:v2.0
              ports:
                # The HTTP port
                - "80:80"
                # The Web UI (enabled by --api.insecure=true)
                - "8080:8080"
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock:ro"
              command:
                - --api.insecure=true
                - --providers.docker
                - --providers.docker.exposedByDefault=false
                - --providers.docker.network=traefik
                - --entrypoints.web.address=:80
                - '--providers.docker.defaultRule=Host(`{{ normalize .Name }}.depot.lan`)'
              networks:
                - traefik
          networks:
            traefik:
              external: true
systemd:
  units:
  - name: traefik.service
    enabled: true
    contents: |-
      [Unit]
      Description=Traefik Router Container
      After=docker.service depot-env.service
      Requires=docker.service depot-env.service

      [Service]
      Restart=always
      EnvironmentFile=-/etc/sysconfig/mediadepot
      TimeoutStartSec=0
      Restart=always
      WorkingDirectory=/opt/mediadepot/systemd/traefik/
      ExecStartPre=-/usr/bin/docker-compose down -v
      ExecStartPre=-/usr/bin/docker-compose rm -v
      ExecStartPre=-/usr/bin/docker-compose pull
      ExecStart=/usr/bin/docker-compose up
      ExecStop=/usr/bin/docker-compose down -v

      [Install]
      WantedBy=multi-user.target
      WantedBy=docker.service
